version: '3.8'

services:
  booking-core:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env  # File .env từ host sẽ được load vào container
    volumes:
      - ./uploads:/app/uploads  # Mount uploads folder để persist files
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Uncomment nếu bạn cần database local
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: booking_db
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
